version: 2
jobs:
  test_prod:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Host'
          command: './node_modules/.bin/firebase deploy -P production --token=$FIREBASE_TOKEN'

workflows:
  version: 2
  build_test_host:
    jobs:
      - test_prod:
          filters:
            branches:
              only: master