version: 2
jobs:
  test_prod:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Install'
          command: 'npm install -g firebase-tools'
      - run:
          name: 'Host'
          command: 'firebase deploy --token=$FIREBASE_TOKEN --non-interactive'

workflows:
  version: 2
  build_test_host:
    jobs:
      - test_prod:
          filters:
            branches:
              only: master